# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }} [ubuntu]
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # Clean cache
      - run: yarn cache clean
      # Run info workspaces
      - run: yarn workspaces info
      # Install dependencies on Workspaces
      - run: yarn workspaces run installPackage
      # Install dependencies
      - run: yarn install
        # Vitest
      #- run: yarn workspaces run test:vitest
        # Jest
      #- run: yarn workspaces run test:jest
        
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }} [macos]
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # Clean cache
      - run: yarn cache clean
      # Run info workspaces
      - run: yarn workspaces info
      # Install dependencies on Workspaces
      - run: yarn workspaces run installPackage
      # Install dependencies
      - run: yarn install
        # Vitest
      #- run: yarn workspaces run test:vitest
        # Jest
      #- run: yarn workspaces run test:jest

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }} [windows]
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # Clean cache
      - run: yarn cache clean
      # Run info workspaces
      - run: yarn workspaces info
      # Install dependencies on Workspaces
      - run: yarn workspaces run installPackage
      # Install dependencies
      - run: yarn install
        # Vitest
      #- run: yarn workspaces run test:vitest
        # Jest
      #- run: yarn workspaces run test:jest
